### ISSUE TITLE
UnicodeDecodeError (utf-8 codec can't decode byte 0xff in position 0: invalid start byte)

### ISSUE THREAD

**Issue by AlexeyKovynev** [rbonghi/docker-dropbox-app#5]
Hi. I launched your dropbox container and it worked perfectly for some time and has already synchronized ~500 files, but then it stopped and I couldn't relauch it anymore. I looked into logs and found this info:

> DropboxSync [[32mSTART[0m]
> 2019-06-16 17.40.16.jpg is already synced [stats match]
> лира9.jpg is already synced [stats match]
> 2019-06-16 18.09.29.jpg is already synced [stats match]
> 2019-06-01 12.39.57-2.jpg exists with different stats, downloading
> Traceback (most recent call last):
>   File "DropBoxSync.py", line 396, in <module>
>     updown.syncFromLocal()
>   File "DropBoxSync.py", line 149, in syncFromLocal
>     data = f.read()
>   File "/usr/local/lib/python3.7/codecs.py", line 322, in decode
>     (result, consumed) = self._buffer_decode(data, self.errors, final)
> **UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte**
> disconnected
![dropbox](https://user-images.githubusercontent.com/5086678/62013893-385dcb00-b1a2-11e9-99bb-b9f6428e2c31.png)
 
I'm not familiar with Python, but I found some info on stackoverflow related to this issue:
[https://stackoverflow.com/questions/42339876/error-unicodedecodeerror-utf-8-codec-cant-decode-byte-0xff-in-position-0-in](url)

**Comment by rbonghi** [comment]
Hi @AlexeyKovynev ,

Thank you for your issue, I'm checking soon!

**Comment by AlexeyKovynev** [comment]
Hi @rbonghi
Have you had some time for this issue? Are there any updates?
I cannot found any alternative docker container (that uses token authorization), and this one does not work :(
It would be really great if you can look into this issue, I'm sure it should not take a lot of time.
Thank you!

**Comment by akolechkin** [comment]
https://github.com/rbonghi/docker-dropbox-app/blob/master/DropBoxSync.py#L148 i think this issue goes from there, actually it will fail on any binary file because it tries to open a file as a text one.

**Comment by rbonghi** [comment]
Hi @akolechkin,
Thank you for your post.
I apologize, but was really difficult for me follow this project in my last months. I hope to fix for this week

**Comment by rbonghi** [comment]
This issue I hope now is fixed.

I update the Dropbox pipeline, should be work fine.
