### ISSUE TITLE
Sync 2 ways both from local and Dropbox

### ISSUE THREAD

**Issue by lbngoc** [rbonghi/docker-dropbox-app#6]
In my case, I want to sync 2 ways both from my local and from my Dropbox.
I tried with 2 params "--fromLocal" and "--fromDropbox" at same time but I get this error: `At most one of --fromDropbox or --fromLocal is allowed`
Could you please show me how to do this?

**Comment by rbonghi** [comment]
I rearrange the script now and can sync at the same time.
I change now the policy of this options:

* **--fromLocal** Will be overwriten from your PC follder to Dropbox
* **--fromDropbox** Will be overwriten from Dropbox to your PC folder

This option works when the node startup. if you do not select nothing, you will see like the real dropbox app a file called **conflict**

Keep me posted if there are other issues
