### ISSUE TITLE
LookupError('restricted_content', None)

### ISSUE THREAD

**Issue by christiansicari** [rbonghi/docker-dropbox-app#7]
Running docker-compose with or without specifying the command option I got this error 

`dropbox_1  | DropboxSync [START]
dropbox_1  | Directory is empty, start first download
dropbox_1  | Traceback (most recent call last):
dropbox_1  |   File "DropBoxSync.py", line 394, in <module>
dropbox_1  |     updown.syncFromDropbox()
dropbox_1  |   File "DropBoxSync.py", line 102, in syncFromDropbox
dropbox_1  |     res = self.download(subfolder, nname)
dropbox_1  |   File "DropBoxSync.py", line 263, in download
dropbox_1  |     md, res = self.dbx.files_download(path)
dropbox_1  |   File "/usr/local/lib/python3.7/site-packages/dropbox/base.py", line 1115, in files_download
dropbox_1  |     None,
dropbox_1  |   File "/usr/local/lib/python3.7/site-packages/dropbox/dropbox.py", line 296, in request
dropbox_1  |     user_message_locale)
dropbox_1  | dropbox.exceptions.ApiError: ApiError('665a583f1e067c47f24ab0f538e997fa', DownloadError('path', LookupError('restricted_content', None)))
`

**Comment by rbonghi** [comment]
Hi @christiansicari 

I will check soon!

**Comment by rbonghi** [comment]
This bug should be fixed now.
I rewrote the dropbox sync script and now I manage this error.
Keep me posted if this error appear again.
