### ISSUE TITLE
fromDropbox crash after first sync

### ISSUE THREAD

**Issue by christiansicari** [rbonghi/docker-dropbox-app#8]
If I run compose the first time I am to sync all remote dirs and files, but just it finish to sync I get this error
`Traceback (most recent call last):
dropbox-download    |   File "DropBoxSync.py", line 389, in <module>
dropbox-download    |     do_every(args.interval, updown.syncFromDropbox())
dropbox-download    |   File "DropBoxSync.py", line 51, in do_every
dropbox-download    |     worker_func ()
dropbox-download    | TypeError: 'NoneType' object is not callable
`

And I have to restart the container in order to sync new added files

**Comment by rbonghi** [comment]
I think is something connected with this #5

**Comment by christiansicari** [comment]
Hi, thank you for the reply. 
I don't have binary files to synchronize.
Therefore if I upload new files in Dropbox and after that, I restart the container, the local directory is updated. But when it finishes scanning all new files he crashes with the same error

**Comment by rbonghi** [comment]
like issue #7 this issue should be fixed.
