### ISSUE TITLE
Doesn't work on a Raspberry 3 (ARM v7)

### ISSUE THREAD

**Issue by bdovaz** [rbonghi/docker-dropbox-app#9]
This image claims to work on "ARM and x86." (Hub Docker)

I think that it has to do with the image architecture:

https://hub.docker.com/r/rbonghi/dropbox/tags

OS/ARCH
linux/amd64

Error:

```
dropbox is up-to-date
Attaching to dropbox
dropbox    | standard_init_linux.go:211: exec user process caused "exec format error"
```

"uname -a" output:

```
Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
```

**Comment by rbonghi** [comment]
I think after ages I fixed it! 934f2e9b76825ee06776dc5b530389e6cca13af6

In my next release should be usable on rasp as well :-)

**Comment by bdovaz** [comment]
LOL, two and a half years later 🤣

Thanks anyway!

**Comment by rbonghi** [comment]
I completely forgot this repo 🤦‍♂️
😂😂
